version: '3'
services:
  dev:
    container_name: aurl-dev
    build: docker/dev
    volumes:
      - .:/workspace/2022-is-experiments2-team-3
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - "10027:22"
  # test:
  #   container_name: aurl-test
  #   build: docker/test
  #   volumes:
  #     - .:/workspace/2022-is-experiments2-team-3
  exp:
    container_name: aurl-exp
    build: docker/exp
    volumes:
      - .:/workspace/2022-is-experiments2-team-3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]