version: '3'
services:
  exp:
    container_name: aurl-exp
    build: .
    volumes:
      - ../..:/workspace/2022-is-experiments2-team-3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]